server:
  port: 8081
spring:
  application:
    name: service-provider
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.leyou.service.pojo
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    com.leyou.service.dao: debug
#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://127.0.0.1:10086/eureka
